"""initial schema

Revision ID: 6b931382ca35
Revises: 
Create Date: 2026-08-27 05:19:16.603425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b931382ca35'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_contamination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('registry', sa.String(length=80), nullable=False),
    sa.Column('habitation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_contamination_parameter'), 'historical_contamination', ['parameter'], unique=False)
    op.create_index(op.f('ix_historical_contamination_village_id'), 'historical_contamination', ['village_id'], unique=False)
    op.create_index(op.f('ix_historical_contamination_year'), 'historical_contamination', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_contamination_year'), table_name='historical_contamination')
    op.drop_index(op.f('ix_historical_contamination_village_id'), table_name='historical_contamination')
    op.drop_index(op.f('ix_historical_contamination_parameter'), table_name='historical_contamination')
    op.drop_table('historical_contamination')
    # ### end Alembic commands ###
